server:
  port: 8080


distribution:
  cacheSize: 2000
  poolSize: 4
  hostName: 172.16.33.119
  port: 1800
  queueManager: DFWTINTRA
  channel: JAVA.CHANNEL
  ccsid: 1208
  queueName: DXP_TO_GGFW
  minConcurrency: 1
  maxConcurrency: 2
  keepAliveSeconds: 3000
  queueCapacity: 20000
  threadNamePrefix: 119-DFWTINTRA-
  otherInputQueue:
    - 172.16.33.119|1800|DFWTINTRA|JAVA.CHANNEL|1208|DXP_TO_GGFW|1|2|3000|20000|119-DFWTINTRA-
  second:
    hostName: 172.16.33.54
    port: 1800
    queueManager: DFWTINTRA
    channel: JAVA.CHANNEL
    ccsid: 1381
    sessionCacheSize: 100
  third:
    hostName: 172.16.33.54
    port: 1800
    queueManager: DFWTINTRA
    channel: JAVA.CHANNEL
    ccsid: 1381
    sessionCacheSize: 100
  otherOutputQueue:
    - 172.16.33.95|1800|DFWTINTRA|JAVA.CHANNEL|1208|100
  rabbitOutputQueue:
    host: 172.16.33.14
    port: 5672
    username: admin
    password: admin
    virtualHost: /ase
    cacheModel: CONNECTION
    channelCacheSize: 25
    connectionCacheSize: 16
    connectionLimit: 32
  rabbitOtherOutputQueue:
    - 172.16.33.14|5672|admin|admin|ase|CONNECTION|25|16|32
  conditionMutualExclusion: true
  # 优先级第一 map key:dxpid, value: 队列名称 如: {DXPENT0000011951: DXP_11951_ENT}
  dxpidDistribution: {}
  # 优先级第二 map key:msgtype, value: 队列名称 如: {CEB312Message: DXP_11951_ENT}
  msgtypeDistribution: {}
  # 优先级第三 map key: 队列名称, value: 比重 如: {GGFW_TO_ENT: 1, GGFW_TO_ENT_INVT: 1}
  percentageDistribution: {}
  # 前面三个没有，才执行最后一个 列表格式，随机分发
  randomDistribution:
  # 所有没有区配到，就转发到默认队列,队列后面加一个:号,走second队列管理器, 两个::号走third队列管理器
  defaultQueue: GGFW_TO_ENT

logging:
  config: classpath:logback-spring.xml
